projects:
  globals:
    stage: example
    environment: uw2
    account_number: "012345678901"

  terraform:
    vpc:
      workspace_enabled: true
      terraform_version: 0.13.3
      triggers:
        - ue2-example-vpc
      vars:
        cidr_block: "10.1.0.0/16"
        nat_gateway_enabled: false
        nat_instance_enabled: true
        nat_instance_type: "t3.micro"
